### ISSUE TITLE
About the .txt in data_dir/

### ISSUE THREAD

**Issue by mawei-north** [XLearning-SCU/2022-CVPR-AirNet#19]
Thank you very much for your excellent work. What is the purpose of providing .txt files in data_dir/ that contain the names of the rain and haze datasets?

**Comment by XLearning-SCU** [comment]
Thanks for your attention to our work. It is mainly because of the my poorly programming skills in 2021. At that time, I use the .txt file to record the path of the input image to avoid the memory cost of directly loading all of the training image at the beginning of the training. In fact, you could avoid using the .txt file and modify the dataloader to directly capture the name list via glob.glob, which is more elegant and easy to use.
