### ISSUE TITLE
Questions about the tasks

### ISSUE THREAD

**Issue by Booooooooooo** [XLearning-SCU/2022-CVPR-AirNet#6]
I noticed that you have considered denoising, deraining and dehazing tasks in your work, what were the reasons for choosing these three tasks? For example, why did you not include tasks such as super-resolution, as considered in Image Processing Transformer. I am very curious about the performance if more tasks were included. Are there any experiments on this?

**Comment by XLearning-SCU** [comment]
Thanks for your question. The motivations of our paper is to propose a novel network which could handle various corruptions types and levels without prior knowledge, which is closer to the real-world cases, e.g., self-driving car. To this end, we test our model on image deraining and dehazing to verify the effectiveness on different corruption types.  We also select denoising with sigma=15, 25, 50 to validate the performance on various corruption levels. All of above corruption types are self-driving cars usually suffered in the wild and this is why we considered denoising, deraining and dehazing in our work.
For SR, we do not select it under the following considerations, 1) the resolutions of cameras in self-driving cars are usually fixed and sufficient, we do not find the situations where the resolution will be decreased,  2) it will be a tough problem to determine the SR scale (or ratio) for a given low-resolution image. IPT is a general model where users determine the SR scale (or ratio) and avoid above problem.
For other tasks, we only test our model on motion deblurring (GOPRO) dataset, which is also usually occurred in the wild. PSNR is around 28-29, which is even lower than the pioneer of deep deblurring method. Moreover, when we train our model on motion deblurring with other corruption types under all-in-one settings, the performance of other corruption types degrade greatly. We guess it may caused by the following reasons, 1) the distribution of images in GOPRO dataset may be greatly different from other datasets and lead to the optimization problem, which is usually appeared in the multi-task learning, 2) the network of our model may not suitable for motion deblurring, multi-scale structure may be better.

**Comment by Booooooooooo** [comment]
Thank you for your patience and detailed answers!
